services:
  server:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: effecty-server
    restart: unless-stopped
    expose:
      - "8010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /opt/effecty/configuration.toml:/app/configuration.toml:ro
      - effecty-uploads:/app/uploads
    networks:
      - infra-network

networks:
  infra-network:
    external: true
    name: infra-network

volumes:
  effecty-uploads:
